### ISSUE TITLE
Is there an unintentional mismatch for OKE version?

### ISSUE THREAD

**Issue by abatilo** [oracle-quickstart/oci-hpc-oke#3]
In the terraform, the version of Kubernetes is 1.27:
https://github.com/oracle-quickstart/oci-hpc-oke/blob/622a6516511cfc3e684012f0588099931b687348/terraform/rdma/main.tf#L23

But the image that needs to be imported is 1.26:
https://github.com/oracle-quickstart/oci-hpc-oke/blob/622a6516511cfc3e684012f0588099931b687348/docs/running-rdma-workloads-on-oke.md

Should I expect that these two are still compatible?

**Comment by OguzPastirmaci** [comment]
They are compatible. OKE follows the [Kubernetes version skew support policy](https://kubernetes.io/docs/setup/release/version-skew-policy/). Running 1.26 nodes in worker pools in a 1.27 cluster is supported.
