### ISSUE TITLE
Ops Nodes Gotting time-out during creation

### ISSUE THREAD

**Issue by ChristoPedro** [oracle-quickstart/oci-hpc-oke#31]
We are trying to deploy a Cluster with H100 without RDMA Cluster. When apply the stack using resource manage, the Operations node never got Active and Ready causing a Time Out on the Terraform destroying the GPU node pool that was Active.

Using the recommended Image that was uploaded to custom images on OCI and the recommended node size.

**Comment by arnaudfroidmont** [comment]
Did you also use the imported image on the OPS nodes?

**Comment by OguzPastirmaci** [comment]
@ChristoPedro do you still have this issue? Did you try what @arnaudfroidmont recommended?

**Comment by OguzPastirmaci** [comment]
@ChristoPedro closing this issue due to no response. Please create a new issue if you see the same problem again.
