### ISSUE TITLE
Is SR-IOV strictly needed for improved bandwidth in RDMA clusters?

### ISSUE THREAD

**Issue by abatilo** [oracle-quickstart/oci-hpc-oke#4]
The RDMA docs mention that SR-IOV functions are only enabled in Phoenix and Osaka:
https://github.com/oracle-quickstart/oci-hpc-oke/blob/622a6516511cfc3e684012f0588099931b687348/docs/running-rdma-workloads-on-oke.md#L5

If the GPUs being provisioned are in another region, should it be alright to skip any steps related to SR-IOV and to disable those values in the relevant helm charts?

Is it possible to enable only RDMA?

**Comment by OguzPastirmaci** [comment]
Currently, we are using Virtual Functions for exposing RDMA interfaces as an allocatable resource. In other regions, you can use the host network directly, but it will not provide the same flexibility as using VFs.

We are currently working on adding VF support in other regions. Please reach out to your Oracle account manager if you're interested in using a different region.
