### ISSUE TITLE
Bug: system node pool disables default cloud init but doesn't specify another one to use

### ISSUE THREAD

**Issue by abatilo** [oracle-quickstart/oci-hpc-oke#5]
The system node pool disables the default cloud init, but doesn't specify what cloud init to override it with:
https://github.com/oracle-quickstart/oci-hpc-oke/blob/622a6516511cfc3e684012f0588099931b687348/terraform/rdma/main.tf#L43

When this is disabled, a required value in the underlying OKE module is not set.

**Comment by OguzPastirmaci** [comment]
Thanks for the catch!

Fixed with #7
