### ISSUE TITLE
Bug: Documented terraform creates workers that are unable to join the OKE cluster

### ISSUE THREAD

**Issue by abatilo** [oracle-quickstart/oci-hpc-oke#6]
If you create a cluster using the sample terraform under the `terraform` directory, your nodes will fail to join the actual OKE control plane.

Excerpt from `/var/log/messages`:
```
Oct 16 13:53:30 inst-rfryj-default proxymux-client[6787]: time="2023-10-16T13:53:30Z" level=info msg="Executing node bootstrap request" endpoint=/workerNodeBootstrap method=GET privateIP=10.0.153.51
Oct 16 13:53:30 inst-rfryj-default proxymux-client[6787]: time="2023-10-16T13:53:30Z" level=error msg="Request failed" endpoint=/workerNodeBootstrap error="Service error:Forbidden. node not authorized. http status code: 403. Opc request id: 0A12A6DDC7A54E06969A664E909F0259/7ECE8DBF97D34B9D937168E775432DCD/EABAC52EE1E944F58CB7D1880CB9BE7B" method=GET privateIP=10.0.153.51
```

I believe this is related to having the OKE module NOT create IAM resources:
https://github.com/oracle-quickstart/oci-hpc-oke/blob/622a6516511cfc3e684012f0588099931b687348/terraform/rdma/main.tf#L37

**Comment by OguzPastirmaci** [comment]
Can you please confirm that you have followed the steps listed [here](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengdynamicgrouppolicyforselfmanagednodes.htm)?

**Comment by OguzPastirmaci** [comment]
`create_iam_resources` creates those resources, but the default is false because usually, the user who's deploying the cluster does not have the required permissions in the tenancy to create those IAM resources. We've added those policies to the tenancy for you. Closing the issue but let us know if you see any issues.
